---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediplus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mediplus
  template:
    metadata:
      labels:
        app: mediplus
    spec:
      containers:
      - name: mediplus
        image: christianchika/mediplus:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mediplus-service
spec:
  type: ClusterIP
  selector:
    app: mediplus
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediplus-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - DOMAIN_PLACEHOLDER
    secretName: mediplus-tls
  rules:
  - host: DOMAIN_PLACEHOLDER
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mediplus-service
            port:
              number: 80
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediplus-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Christianchika/kubernetes-manifest.git"
    targetRevision: HEAD
    path: "."
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true








