apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: okoro.christianpeace@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
# Deployment, Service, Ingress, ArgoCD Application here
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediplus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mediplus
  template:
    metadata:
      labels:
        app: mediplus
    spec:
      containers:
      - name: mediplus
        image: your-docker-image:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mediplus
spec:
  selector:
    app: mediplus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediplus
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: mypodsix.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mediplus
            port:
              number: 80
  tls:
  - hosts:
    - mypodsix.online
    secretName: mediplus-tls
